spring:
  application:
    name: GSM-Place

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope: email, profile

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true
        show_sql: true

  ai:
    openai:
      api-key: ${OPENAI_KEY}

  jwt:
    access-key: ${ACCESS_KEY}
    refresh-key: ${REFRESH_KEY}
    access-expired: 9999999999
    refresh-expired: 172800000

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket-name: ${AWS_BUCKET_NAME}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB