spring:
  application:
    name: GSM-Place

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope: email, profile, openid

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        show_sql: true

  ai:
    openai:
      api-key: ${OPENAI_KEY}

  jwt:
    access-key: ${ACCESS_KEY}
    refresh-key: ${REFRESH_KEY}
    access-expired: 3600000
    refresh-expired: 172800000